// Action constants
export const LOAD_ITEMS_SUCCESS = 'LOAD_ITEMS_SUCCESS';
export const LOAD_NEXT_ITEMS = 'LOAD_NEXT_ITEMS';
export const LOAD_SEARCHED_ITEMS = 'LOAD_SEARCHED_ITEMS';
export const REQUEST_ITEMS = 'REQUEST_ITEMS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const LOAD_HOME_PRODUCTS = 'LOAD_HOME_PRODUCTS';
export const LOAD_PRODUCT_DETAILS = 'LOAD_PRODUCT_DETAILS';